name: reduce-llm
channels:
  - anaconda
  - pytorch-nightly
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - tokenizers
  - scikit-optimize
  - nltk
  - pyspellchecker
  - libiconv
